### ISSUE TITLE
Pro License key doesn't work and unable to get help

### ISSUE THREAD

**Issue by poweredtriple** [loongmxbt/AxMath#2]
I've purchased a license in 2019 or so. I upgraded my computer, and now I'm unable to activate my AxMath. My emails are being ignored. I'm unsure how to ask for help. Unable to join Slack channel for support since I don't have an account in the workspace - seems to be for devs only, not open to the public.

**Comment by loongmxbt** [comment]
@greycouncil Please download the latest version here https://www.axsoft.co/ . And use this key to activate: M2U6C-8PMMS-CWY32-CLAC4-HS9Z9 . Make sure you connect to internet and vpns off.
