### ISSUE TITLE
Cannot apply key by license file.

### ISSUE THREAD

**Issue by cesaryuan** [loongmxbt/AxMath#4]
Around 2019, I bought Axmath to help me write formulas, which helped me a lot. To be honest, it is easier to use than mathtype software, and it also supports exporting latex, which is great!

But recently, there was a virus on my computer. After I killed the virus, the axmath was deactivated. When I tried to reactivate it, I was prompted to use the license to apply a key. But got an error.

![image](https://github.com/loongmxbt/AxMath/assets/35998162/2ec5352f-3470-4718-bd82-4e1328b6da2b)

But I did use the license of the corresponding code.

![image](https://github.com/loongmxbt/AxMath/assets/35998162/2c24cbbc-f731-4d60-8130-cd19fbc18f42)

Can you help me find out what the problem is? I would be very grateful.

**Comment by loongmxbt** [comment]
Hi, please download the latest version and use this new activation code:
M2U65-PZ23K-3EWQ6-LBTPM-MTAZQ

Cesaryuan ***@***.***> 于2024年3月31日周日 12:26写道：

**Comment by cesaryuan** [comment]
Thank you so much!
