### ISSUE TITLE
error activation when change laptop

### ISSUE THREAD

**Issue by joparna** [loongmxbt/AxMath#5]
i'm buy axmath lisense M2S7Z-UU3Q4-TF4HT-322TX-ERTZH on mey 2022 then succes registration. but when my laptop broken cant on, i purchase new laptop but cant succes when register again with the same license till now. i had send email but no respon till now

**Comment by signal-rider** [comment]
I can't even login to my previous account (where my key was). I want to use it in again after the hard-drive crashed.

**Comment by loongmxbt** [comment]
Hi @joparna, please use this key: M2UBP-MXZEM-26SSY-CQLRL-KL3Z9
