### ISSUE TITLE
Account login failure

### ISSUE THREAD

**Issue by signal-rider** [loongmxbt/AxMath#7]
Previously, I have cloned the SSD where my axmath was installed and now its asking to register again. But the account associated is not even opening where my key information was stored. Also, I haven't saved my license number. The payment is dated as on June 21, 2023. Please help.

**Comment by loongmxbt** [comment]
Hi @signal-rider, please use this key for AxMath: M2UBP-4FW2L-BVA88-C26NK-B4QZX
